spring.application.name=backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/student_grievance?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Happygamer008
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
